version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    restart: on-failure
    volumes:
      - postgresql:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${DB_NAME} -U $${POSTGRES_USER} -p 5432" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  web:
    image: notmaincode/api_yamdb:latest
    restart: on-failure
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/admin" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/admin" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgresql:
  static_value:
  media_value:
